{
 "title": "Dynamisk Servermiljö",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Kund",
    "query": "\tSELECT computers.clientid as __value, clients.name as __text FROM computers LEFT JOIN Clients ON (Computers.ClientId=Clients.ClientId) Group by clients.clientid"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "content": "\n\n<img src=\"https://uddmor.files.wordpress.com/2011/11/silikon-valle-1.png\">\n"
  },
  {
   "title": "Need Reboot",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n     computers.name AS `Computer Name`,\r\n    IF((Computers.flags & 1024) <> 0, 1, 0) AS `Omstart`\r\nFROM Computers \r\nLEFT JOIN inv_operatingsystem ON (Computers.ComputerId=inv_operatingsystem.ComputerId)\r\nLEFT JOIN Clients ON (Computers.ClientId=Clients.ClientId)\r\nLEFT JOIN Locations ON (Computers.LocationId=Locations.LocationID)\r\n WHERE \r\n((IF((Computers.flags & 1024) <> 0, 1, 0)<>0)) and clients.clientid=$Kund\r\n"
    }
   ]
  },
  {
   "title": "Network traffic out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n(h_computerstatshourly.Dataout) AS value,\r\n (UNIX_TIMESTAMP(LastUpdate))  AS  time_sec ,\r\n  \r\n  name AS metric\r\nFROM h_computerstatshourly \r\nINNER JOIN computers ON h_computerstatshourly.Computerid=computers.computerid\r\nWHERE $__timeFilter(LastUpdate) AND clientid=$Kund AND os LIKE '%server%' \r\nGROUP BY time_sec ASC\r\nOrder by time_sec\r\n"
    }
   ]
  },
  {
   "title": "Enheter",
   "type": "grafana-piechart-panel",
   "description": "Static on clientid",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\nclients.name AS 'Åkerikonsult',\r\n  (UNIX_TIMESTAMP(PCDate)) and PCDate is not null as time_sec,\r\n  Count(*) as value,\r\n  COUNT(computers.computerid) AS 'Server',\r\n  'Server' as metric\r\nFROM computers \r\nLEFT OUTER JOIN clients ON clients.clientid=computers.clientid\r\nLEFT OUTER JOIN locations ON locations.locationid=computers.locationid\r\nWHERE (UNIX_TIMESTAMP(PCDate)) AND computers.clientid=clients.clientid AND `OS` LIKE '%server%'  and clients.clientid=$Kund"
    },
    {
     "rawSql": "SELECT\r\nclients.name AS 'Åkerikonsult',\r\n  (UNIX_TIMESTAMP(PCDate)) and PCDate is not null as time_sec,\r\n  Count(*) as value,\r\n  COUNT(computers.computerid) AS 'Workstation',\r\n  'Workstation' as metric\r\nFROM computers \r\nLEFT OUTER JOIN clients ON clients.clientid=computers.clientid\r\nLEFT OUTER JOIN locations ON locations.locationid=computers.locationid\r\nWHERE (UNIX_TIMESTAMP(PCDate)) AND computers.clientid=clients.clientid AND `OS` NOT LIKE '%server%'  and clients.clientid=$Kund\r\n\r\nORDER BY 'Server' , time_sec ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(DeviceDateLastContact) and DeviceDateLastContact is not null as time_sec,\n  Count(DeviceStatus=1) as value,\n  'Network Devices' as metric\nFROM v_xr_networkdevices \nWHERE UNIX_TIMESTAMP(DeviceDateLastContact) and ClientID=$Kund\nORDER BY time_sec ASC\n"
    }
   ]
  },
  {
   "title": "Network traffic in",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n(h_computerstatshourly.Datain) AS value,\r\n (UNIX_TIMESTAMP(LastUpdate))  AS  time_sec ,\r\n  \r\n  name AS metric\r\nFROM h_computerstatshourly \r\nINNER JOIN computers ON h_computerstatshourly.Computerid=computers.computerid\r\nWHERE $__timeFilter(LastUpdate) AND clientid=$Kund AND os LIKE '%server%' \r\nGROUP BY time_sec ASC\r\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT IFNULL(ROUND(SUM((SELECT COUNT(*) \r\nFROM v_xr_backup_jobs \r\nWHERE BackupJobStatus='Completed' AND BackupJobStartTime > DATE_ADD(NOW(),INTERVAL -30 DAY) \r\nAND clientid=(1 OR 1=0))/(SELECT COUNT(*) FROM v_xr_backup_jobs WHERE BackupJobStatus IN ('Completed','Failed') \r\nAND BackupJobStartTime > DATE_ADD(NOW(),INTERVAL -30 DAY) \r\nAND clientid=(1 OR 1=0)))*100,0),0) AS `value`\r\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND((SUM(IF(hf.approved=2 AND hf.installed=1,1,0)))/SUM(IF(hf.approved=2,1,0))*100) AS `value` \r\nFROM Hotfix AS hf JOIN Computers AS c ON hf.Computerid = c.ComputerId \r\nWHERE (hf.Last_Date >= '0001-01-01 00:00:00') AND clientid=$Kund"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "description": "Static on ComputerID",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Max Load" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n(cpu) AS value,\r\n (UNIX_TIMESTAMP(LastUpdate))  AS  time_sec ,\r\n  \r\n  name AS metric\r\nFROM h_computerstatshourly \r\nINNER JOIN computers ON h_computerstatshourly.Computerid=computers.computerid\r\nWHERE $__timeFilter(LastUpdate) AND clientid=$Kund AND os LIKE '%server%' \r\nGROUP BY time_sec ASC\r\n"
    }
   ]
  },
  {
   "title": "Low HD",
   "type": "table",
   "description": "Green = < 8 GB\nOrange = < 4 GB\nRed = < 2 GB",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\ncomputers.locationid,\r\n   computers.computerid as 'Computer Id',\r\n   computers.name as 'Computer Name',\r\n   clients.name as `Client Name`,\r\n   computers.domain as `Computer Domain`,\r\n   computers.username as `Computer User`,\r\n   drives.letter,\r\n   drives.VolumeName as 'Volume Name' ,\r\n   Drives.Free/1024 as `GB Free`,\r\n   \r\n   CASE WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('CD', 'DVD') THEN 3 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) = 'USB' THEN 2 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('IDE', 'SCSI') THEN 1 WHEN Drives.FileSystem IN('NTFS', 'FAT32', 'FAT', 'HFS', 'ext2', 'ext3', 'ext4', 'btrfs', 'jfs', 'xfs', 'reiser4', 'reiserfs') THEN IF(INSTR(LOWER(Drives.Model), 'usb')>0, 2, 1) ELSE 4 END as `Computer.Drives.Type`,\r\n   IF(INSTR(computers.os, 'server')>0, 1, 0) as `Computer.OS.IsServer`\r\nFROM Computers \r\nLEFT JOIN inv_operatingsystem ON (Computers.ComputerId=inv_operatingsystem.ComputerId)\r\nLEFT JOIN Clients ON (Computers.ClientId=Clients.ClientId)\r\nLEFT JOIN Locations ON (Computers.LocationId=Locations.LocationID)\r\nLEFT JOIN Drives ON (Drives.ComputerId=Computers.ComputerId)\r\n WHERE \r\n((((Drives.Free/1024 < 8)and (CASE WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('CD', 'DVD') THEN 3 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) = 'USB' THEN 2 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('IDE', 'SCSI') THEN 1 WHEN Drives.FileSystem IN('NTFS', 'FAT32', 'FAT', 'HFS', 'ext2', 'ext3', 'ext4', 'btrfs', 'jfs', 'xfs', 'reiser4', 'reiserfs') THEN IF(INSTR(LOWER(Drives.Model), 'usb')>0, 2, 1) ELSE 4 END = '1') AND  (IF(INSTR(computers.os, 'server')>0, 1, 0)<>0))))\r\nand computers.clientid=$Kund"
    }
   ]
  },
  {
   "title": "MEMORY LOAD",
   "type": "graph",
   "description": "Static on ComputerID",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "Max Load" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n(100-mem) AS value,\r\n (UNIX_TIMESTAMP(LastUpdate))  AS  time_sec ,\r\n  \r\n  name AS metric\r\nFROM h_computerstatshourly \r\nINNER JOIN computers ON h_computerstatshourly.Computerid=computers.computerid\r\nWHERE $__timeFilter(LastUpdate) AND clientid=$Kund AND os LIKE '%server%' \r\nGROUP BY time_sec ASC\r\n"
    }
   ]
  }
 ]
}